language: python
python:
  - "2.7"
before_install:
    - pip install -U setuptools
    - sudo add-apt-repository -y ppa:pyside/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq libusb-dev python-pyside libffi-dev libjpeg8-dev libudev-dev libusb-1.0-0-dev python-dbus
    - ln -s /usr/lib/python2.7/dist-packages/PySide /usr/lib/python2.7/dist-packages/*dbus* ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - git clone git://github.com/signal11/hidapi.git /tmp/hidapi
    - cd /tmp/hidapi
    - ./bootstrap
    - ./configure
    - make
    - sudo make install
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install cffi
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:  py.test --cov spreads --cov spreadsplug tests
after_success: coveralls
